stages:
  - test
  - build

variables:
  IMAGE_NAME: "danielariza1/chatbot-devops"
  TAG: "latest"

test:
  stage: test
  image: python:3.10
  script:
    - pip install pytest
    - pytest

docker_build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t $IMAGE_NAME:$TAG .
    - echo "🔑 Logueando en DockerHub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "🚀 Subiendo imagen..."
    - docker push $IMAGE_NAME:$TAG
  only:
    - main
