name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar pruebas
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chatbot-devops:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-devops:latest
